### PR TITLE
Try android minSdk 21

### PR DESCRIPTION
**Pull request by appt2**
using api 21 to work all version android

### CODE REVIEW

**Comment by larsgrefer** [comment]
Just setting the declared minSdk to 21 is not enough.

The java library actually uses API's which are only available on SDK 26+.

**Comment by appt2** [comment]
> Just setting the declared minSdk to 21 is not enough.
> 
> The java library actually uses API's which are only available on SDK 26+.

I tested it on my mother's mobile phone and it worked well. My mother's mobile phone is Android 6 and it executed the sass code well

**Comment by larsgrefer** [comment]
Could you add a test case for sdk 21 here: https://github.com/larsgrefer/dart-sass-java/blob/f30ba9372267589d549df6255efafd8b0d49e528/.github/workflows/gradle.yml#L60

**Comment by appt2** [comment]
> Could you add a test case for sdk 21 here:
> 
> https://github.com/larsgrefer/dart-sass-java/blob/f30ba9372267589d549df6255efafd8b0d49e528/.github/workflows/gradle.yml#L60

im testing
 https://github.com/appt2/dart-sass-java/actions/runs/8254132339

**Comment by appt2** [comment]
It is very strange that my program is at least sdk 21 and it runs the code well, but the actions get errors
<a href ="https://github.com/appt2/Ghost-web-ide
" > my app </a>

**Comment by larsgrefer** [comment]
This error is trivial. The library has minSdk 21, but the demo app which is tested has minSdk 26

**Comment by appt2** [comment]
> This error is trivial. The library has minSdk 21, but the demo app which is tested has minSdk 26

So, the trial program needs to update the SDK?

**Comment by larsgrefer** [comment]
@appt2 This is the error I'd expect on sdk 21: https://github.com/larsgrefer/dart-sass-java/actions/runs/8256090593/job/22584005194?pr=480#step:6:308

**Comment by appt2** [comment]
> @appt2 This is the error I'd expect on sdk 21: https://github.com/larsgrefer/dart-sass-java/actions/runs/8256090593/job/22584005194?pr=480#step:6:308

It is strange that your library works well on old mobile phones

**Pull request merged**
